### ISSUE TITLE
game speed bugs

### ISSUE THREAD

**Issue by TheVektor** [gtaco-op/vc-coop#10]
If you keep pressing aim button the game's speed is going very fast.
Spawned cars' physics are very fast too like after picking up adrenaline

**Comment by ZeyadAhmed** [comment]
yep that happens with me , that is strange tho I thought its a asi that I have

**Comment by LemonHaze420** [comment]
Will look into this after investigating the weapon crashes.

**Comment by LemonHaze420** [comment]
This is caused by the CPad hook in CGame.cpp.

A workaround is to comment the below line:-
``original_GetPad = (CPad*(__cdecl*)(int))DetourFunction((PBYTE)0x4AB060, (PBYTE)GetPad_Hook);``

It's unneeded at this point, but may be utilized in the future. It's also worth noting that the SPACE button also causes the same issues when in a vehicle.
